# Generated by Django 3.2.3 on 2023-12-05 20:40

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20231206_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя: '),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия: '),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже есть'}, help_text='Не более 150 символов. Только буквы и цифры, символы @+-', max_length=150, unique=True, validators=[users.validators.validator_username], verbose_name='Логин'),
        ),
    ]
